version: '3.5'

volumes:
  beanstalk_data:
    driver: local

services:
  beanstalk:
    image: xdimedrolx/beanstalkd:1.11
    command: "beanstalkd -b /beanstalk"
    ports:
      - 11300:11300
    volumes:
      - beanstalk_data:/beanstalk